services:
    coddictdevextra.entitymanager:
        class:        Coddict\DevExtraBundle\Services\EntityManager
        arguments:    ["@service_container"]
    coddictdevextra.composer:
        class:        Coddict\DevExtraBundle\Services\ComposerService
        arguments:    ["@service_container"]
    coddictdevextra.packagistsearch:
        class:        Coddict\DevExtraBundle\Services\PackagistSearchService
        arguments:    ["@service_container"]
    coddictdevextra.console:
        class:        Coddict\DevExtraBundle\Services\ConsoleService
        arguments:    ["@service_container"]